# Imagen base con ROS Noetic, Gazebo y herramientas de desarrollo
FROM osrf/ros:noetic-desktop-full

# Instalar TurtleBot3 y SLAM (gmapping)
RUN apt-get update && apt-get install -y \
    ros-noetic-turtlebot3 \
    ros-noetic-turtlebot3-simulations \
    ros-noetic-slam-gmapping

# Definir variable de entorno para el modelo del robot
ENV TURTLEBOT3_MODEL=burger

# Comando de inicio al correr el contenedor
CMD ["bash", "-c", "source /opt/ros/noetic/setup.bash && roslaunch turtlebot3_gazebo turtlebot3_world.launch"]
