
version: '3'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - red_monitorizacion

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - red_monitorizacion

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    container_name: zabbix-server
    environment:
       DB_SERVER_HOST: zabbix-db
    ports:
      - "10051:10051"
    networks:
      - red_monitorizacion

  zabbix-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
    networks:
      - red_monitorizacion

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-db
      DB_SERVER_PORT: 3306
      DB_SERVER_DBNAME: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix

    ports:
      - "8081:8080"
    networks:
      - red_monitorizacion

networks:
  red_monitorizacion:
