global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['zabbix-agent:10050', 'node-exporter:9100']

  - job_name: 'qemu-vms'
    static_configs:
      - targets: ['192.168.200.188:9100', '192.168.200.195:9100', '192.168.200.234:9100'] 
